version: "3.9"

services:
  front:
    build: ./front
    ports:
      - "3000:3000"
    environment:
      FRONT_PORT: 3000
    env_file:
      - .env
    depends_on:
      - back

  back:
    build: ./back
    ports:
      - "3001:3001"
    environment:
      BACK_PORT: 3001
    env_file:
      - .env
    depends_on:
      - db

  db:
    image: postgres:16
    environment:
      POSTGRES_USER: pacto_user
      POSTGRES_PASSWORD: pacto_pass
      POSTGRES_DB: pacto
    volumes:
      - pacto_postgres_data:/var/lib/postgresql/data

volumes:
  pacto_postgres_data: