services:
  front:
    image: node:22
    working_dir: /app
    volumes:
      - ./front:/app
    ports:
      - "3000:3000"
    command: npx nuxt dev --host 0.0.0.0

  back:
    image: node:22
    working_dir: /app
    volumes:
      - ./back:/app
    ports:
      - "3001:3001"
    env_file:
      - ./back/.env
    depends_on:
      - db
    command: npx nodemon src/server.js

  db:
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: mydb
    ports:
      - "5432:5432"
    volumes:
      - pacto_postgres_data:/var/lib/postgresql/data

volumes:
  pacto_postgres_data:
