services:
  front:
    image: node:22
    working_dir: /app
    volumes:
      - ./front:/app
    env_file:
      - .env
    command: npx nuxt dev --host 0.0.0.0 --port $NUXT_PORT
    ports:
      - "3000:$NUXT_PORT"

  back:
    image: node:22
    working_dir: /app
    volumes:
      - ./back:/app
    ports:
      - "3001:3001"
    env_file:
      - .env
    depends_on:
      - db
    command: npx nodemon src/server.js

  db:
    image: postgres:16
    environment:
      POSTGRES_USER: pacto_user       # identifiant utilisé dans PG_URL
      POSTGRES_PASSWORD: pacto_pass   # mot de passe utilisé dans PG_URL
      POSTGRES_DB: pacto              # nom de la DB utilisé dans PG_URL
    ports:
      - "5432:5432"
    volumes:
      - pacto_postgres_data:/var/lib/postgresql/data

volumes:
  pacto_postgres_data:
