services:
  app:
    image: node:22
    working_dir: /app
    volumes:
      - .:/app
      # - node_modules:/app/node_modules
    ports:
      - "3000:3000"
    command: npm run dev -- --host 0.0.0.0

# volumes:
  # node_modules: